import sys

from core.io.SofiaLatticeLoader import SofiaLatticeLoader
from core.io.StatisticsSaver import StatisticsSaver
from core.statistics.LatticeStatistics import LatticeStatistics

__author__ = "Pierre Monnin"


def main():
    print("Lattice statistics")

    if len(sys.argv) != 3:
        print_usage()

    else:
        lattice = SofiaLatticeLoader.load_lattice(sys.argv[1])
        statistics = LatticeStatistics.compute_statistics(lattice)
        StatisticsSaver.save_statistics(statistics, sys.argv[2])


def print_usage():
    print("Usage: latticeStatistics.py lattice.json statistics.json")
    print("\tlattice.json\tJSON file containing the lattice generated by SOFIA")
    print("\tstatistics.json\tName of the file where the statistics of the context will be stored")

if __name__ == '__main__':
    main()
