import argparse

from core.io.LatticeManager import LatticeManager
from core.io.StatisticsSaver import StatisticsSaver
from core.statistics.LatticeStatistics import LatticeStatistics

__author__ = "Pierre Monnin"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("lattice", help="JSON file containing the lattice generated by SOFIA")
    parser.add_argument("statistics", help="Name of the JSON file where the statistics of the lattice will be stored")
    args = parser.parse_args()

    print("SOFIA Lattice statistics")
    lattice = LatticeManager.load_2d_sofia_lattice(args.lattice)
    statistics = LatticeStatistics.compute_statistics(lattice)
    StatisticsSaver.save_statistics(statistics, args.statistics)


if __name__ == '__main__':
    main()
