import argparse

from core.io.StatisticsSaver import StatisticsSaver

__author__ = "Pierre Monnin"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("trilattice", help="File containing the trilattice generated by DataPeeler")
    parser.add_argument("statistics", help="File where the statistics of the trilattice will be stored")
    args = parser.parse_args()

    print("Trilattice statistics")

    concepts_count = 0
    with open(args.trilattice, 'r') as trilattice:
        for i, current_line in enumerate(trilattice):
            concepts_count += 1

    statistics = {"triconcepts-count": concepts_count}
    StatisticsSaver.save_statistics(statistics, args.statistics)


if __name__ == '__main__':
    main()
